language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.3
      brew_packages: rust
    - os: osx
      osx_image: xcode8.3
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-mozilla-security/rust-updates'
    packages:
      - cargo
