language: r
cache: packages
latex: false
fortran: false
pandoc: false
r_check_args: '--run-donttest'

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: linux
      addons:
        apt:
          sources:
            sourceline: 'ppa:ubuntu-mozilla-security/rust-updates'
          packages: cargo
    - os: osx
      brew_packages: rust
    - os: osx
      osx_image: xcode8.3
      disable_homebrew: true
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages: cargo
